[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc-version = "0.8.25"
optimizer = true
optimizer_runs = 420_000
fuzz_max_global_rejects = 420_000

gas_reports = [
    "BBitsBadges",
    "BBitsSocial",
    "BBitsCheckIn",
    "BBitsBadge7Day",
    "BBitsBadgeFirstClick",
    "BBitsBadgeBearPunk",
    "BBitsRaffle"
]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts",
]